theme: jekyll-theme-slate
[remote "origin"]
    url = [https://github.com/teslyta/Hello_world.git]
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
